language: cpp

compiler: gcc

notifications:
  irc:
    channels:
      - "irc.quakenet.org#unrealarena"
    template:
      - "%{repository_slug} (%{branch}) \"%{commit_message}\" [%{result}]"
      - "%{build_url}"
      - "%{compare_url}"

env:
  - MAP=campgrounds

before_install:
  - travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - travis_retry sudo apt-get -qq update

install:
  - travis_retry sudo apt-get -qq install gcc-4.9 g++-4.9 libxml2 libglib2.0-0 libpng12-0 libjpeg-turbo8 libc6 zlib1g libpcre3
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - travis_retry git clone https://github.com/xonotic/netradient.git
  - cd netradient && make -j8 BUILD=native DEPENDENCIES_CHECK=off binaries-q3map2 && cd ..
  - export PATH="netradient/install:${PATH}"

before_script:
  - export HOMEPATH="${HOME}/.unrealarena/pkg"
  - export MAPVERSION=$(cat "maps/${MAP}/VERSION")
  - export CMNVERSION=$(cat "data/VERSION")
  - export PAKVERSION=$(cat "VERSION")
  - mkdir -pv "${HOMEPATH}"
  - cd data && zip -r9 "${HOMEPATH}/maps-common_${CMNVERSION}.pk3" * && cd ..

script:
  - q3map2 -threads 8 -fs_homebase .unrealarena -fs_game pkg -meta -custinfoparms -keeplights "maps/${MAP}/maps/${MAP}.map"
  - q3map2 -threads 8 -fs_homebase .unrealarena -fs_game pkg -vis -saveprt "maps/${MAP}/maps/${MAP}.map"
  - q3map2 -threads 8 -fs_homebase .unrealarena -fs_game pkg -light -faster "maps/${MAP}/maps/${MAP}.map"
  - cd "maps/${MAP}" && zip -r9 "../../map-${MAP}_${MAPVERSION}.pk3" * && cd ../..
  - zip -d "map-${MAP}_${MAPVERSION}.pk3" "maps/${MAP}.srf" "maps/${MAP}.prt"

# after_success:

# after_failure:

# after_script:

before_deploy:
  - mv -v "${HOMEPATH}/maps-common_${CMNVERSION}.pk3" .
  - zip -9 "maps-common_${PAKVERSION}.pre.zip" "maps-common_${CMNVERSION}.pk3"
  - zip -9 "map-${MAP}_${PAKVERSION}.pre.zip" "map-${MAP}_${MAPVERSION}.pk3"

deploy:
  provider: releases
  api_key:
    secure: wNC/c/1o85wgJwJkEdfluDgNo6mOTL9rxCzxU+ZutsdODdT11GEfeXfBYyPINAqaEa7b6oZX4FXX0M8N0M9I51pSIUmuGdYr0qM/OqxEcL4y6L6mLivCA358zpPhmYus0EuzgJO/2Uy4TlrjNBOov64IT6xNsZ9t11ELurg0tH/KG4OMqRHBJu/Iwi3Uls0Q2/QdiCU9YT4En8Sd61DxieyXU3FiUGD3CFhEl7GbFnURNMHh+3r2T9/CvI2QQgp1vD9lZZH08poNZmmkxuv/HyST7/aAzlwDkNNBuIaW5YvCAuK824rWr8NGp7Zqlc1gR+qyU2hWLDMv3ot/XEQPO3rbehAsyzYqjSrQJScWwPKdq3cI7NttlI3CnCtaEQNpLFitc9n97fg0odcizaOUjwzLANUDZabLE//zm7aXqCB1VcmW8CMcq4um3twV91M49kbrYl9612F/luFewRK6M2UTqELa88VWXKjIg9E6PWlvF0UkhN81iJXuRiCLQsLosCJ85YNlOMx1sVKLKr5hxmvzTAB8SV0tWrroENTCa4uiI8UQ6YVs7TCYoFI+RPVFVfdnI8nxwMdS0cbHEp8Rtb8XHL3DxH4maOHWVSOcDn4AnpPKfzxUoiVs4LK009WtI88eYYbmY59oeElel7Hknq35+0jFEF4v2jRS1AsnkqA=
  file:
    - "maps-common_${PAKVERSION}.pre.zip"
    - "map-${MAP}_${PAKVERSION}.pre.zip"
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: unrealarena/unrealarena-maps

# after_deploy:
